apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app.kubernetes.io/name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: my-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-app
    spec:
      containers:
      - name: my-app
        # image: ttl.sh/blake-demo-unsigned:1h # TODO template this with CI
        image: ttl.sh/blake-demo-signed:1h
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
